name: Install ROS2 humble (Linux only)
description: Install ROS2 humble (Linux only)
runs:
  using: "composite"
  steps:
   - name: Setup ROS2
     uses: ros-tooling/setup-ros@0.7.0
     with:
       required-ros-distributions: humble
